// 英検4級 英熟語・表現 150
// 並び順＝学習順（30個ずつ Day1〜5）。ex/ft の [ ] が熟語とその訳
window.EIKEN_IDIOMS = [
// ---- Day1 ----
{"w": "look for ~", "m": "〜をさがす", "s": [], "ex": "I am [looking for] my cat.", "ft": "私はネコを[さがして]いる。", "tip": "look forは見えないものを目でさがす動作。findは「見つける」という結果。look at（〜を見る）と区別する。"},
{"w": "look at ~", "m": "〜を見る", "s": [], "ex": "[Look at] that big dog!", "ft": "あの大きな犬を[見て]！", "tip": "atは「一点」なので、じっと目を向けるイメージ。see（自然に見える）、watch（動くものをじっと見る）との区別がよく出る。"},
{"w": "look like ~", "m": "〜のように見える", "s": ["〜に似ている"], "ex": "That cloud [looks like] a fish.", "ft": "あの雲は魚の[ように見える]。", "tip": "後ろは名詞。形容詞ならlook happy（うれしそう）でlikeは不要。You look like your mother.＝お母さんに似ている。"},
{"w": "look forward to ~", "m": "〜を楽しみに待つ", "s": [], "ex": "I'm [looking forward to] the school trip.", "ft": "私は修学旅行を[楽しみにしている]。", "tip": "toの後ろは名詞か~ing。look forward to seeing you（会えるのを楽しみにする）の形が出る。toの後ろを動詞の原形にしない。"},
{"w": "look after ~", "m": "〜の面倒を見る", "s": ["= take care of ~"], "ex": "Yuki [looks after] her little brother.", "ft": "ユキは弟の[世話をする]。", "tip": "afterは「後ろについていく」。子どもやペットの後ろについて見守るイメージ。take care of ~と同じ意味で言いかえ問題に出る。"},
{"w": "wait for ~", "m": "〜を待つ", "s": [], "ex": "Please [wait for] me at the station.", "ft": "駅で私を[待って]ください。", "tip": "waitだけだと「待つ」。だれを・何を待つかを言うときはforが必要。wait for the bus（バスを待つ）の形でよく出る。"},
{"w": "listen to ~", "m": "〜を聞く", "s": [], "ex": "I [listen to] music every night.", "ft": "私は毎晩音楽を[聞く]。", "tip": "自分から耳をかたむけて聞くのがlisten to、自然に聞こえるのがhear。聞くものを後ろに置くときはtoを忘れない。"},
{"w": "talk to ~", "m": "〜と話す", "s": ["〜に話しかける"], "ex": "Ken [talked to] his teacher after class.", "ft": "ケンは授業のあと先生と[話した]。", "tip": "talk to ~＝〜に話しかける、talk with ~＝〜と話し合う、talk about ~＝〜について話す。前置詞の区別がよく出る。"},
{"w": "take care of ~", "m": "〜の世話をする", "s": ["〜を大事にする", "= look after ~"], "ex": "I [take care of] our dog every day.", "ft": "私は毎日うちの犬の[世話をする]。", "tip": "careは「注意・世話」。Take care.（気をつけてね）は別れのあいさつ。look after ~と同じ意味で言いかえ問題に出る。"},
{"w": "take a picture", "m": "写真をとる", "s": ["= take a photo"], "ex": "Can I [take a picture] of your dog?", "ft": "あなたの犬の[写真をとって]もいい？", "tip": "「写真をとる」はtakeを使う。とるものはofで続ける。複数ならtake pictures。take - took - taken。"},
{"w": "look around ~", "m": "〜を見て回る", "s": ["周りを見回す"], "ex": "We [looked around] the old town last Sunday.", "ft": "この前の日曜日、私たちは古い町を[見て回った]。", "tip": "around＝ぐるりと。look around the shop「店の中を見て回る」の形で出る。look for（さがす）・look at（見る）と区別。"},
{"w": "take a walk", "m": "散歩する", "s": ["= go for a walk"], "ex": "We [take a walk] in the park on Sundays.", "ft": "私たちは日曜日に公園を[散歩する]。", "tip": "walkはここでは名詞で「散歩」なのでaがつく。go for a walkも同じ意味。take a walk with my dog（犬と散歩する）の形も出る。"},
{"w": "take a break", "m": "ひと休みする", "s": ["休けいする"], "ex": "Let's [take a break] for ten minutes.", "ft": "10分間[ひと休みし]よう。", "tip": "breakは名詞で「休けい」。breakfast（朝食）はfast（断食）をbreak（破る）から。take a restも「休む」の意味。"},
{"w": "get together", "m": "集まる", "s": ["（人と）会う"], "ex": "Let's [get together] at the park after school.", "ft": "放課後、公園に[集まろう]。", "tip": "together＝いっしょに。いっしょになる＝集まる。Let's get together. の形で会話によく出る。meet（会う）に近い。"},
{"w": "get to ~", "m": "〜に着く", "s": ["= arrive at ~", "= reach ~"], "ex": "How can I [get to] the station?", "ft": "どうすれば駅に[着け]ますか。", "tip": "arrive at ~やreach ~と同じ意味。道をたずねる文でよく出る。get home・get hereのように、home・here・thereの前にはtoをつけない。"},
{"w": "get on ~", "m": "〜に乗る", "s": [], "ex": "We [got on] the bus at the station.", "ft": "私たちは駅でバスに[乗った]。", "tip": "onは「上にのる」。バス・電車・自転車に乗るときに使う。車やタクシーはget in ~。反対はget off ~（降りる）。"},
{"w": "get off ~", "m": "〜を降りる", "s": [], "ex": "Please [get off] the train at the next station.", "ft": "次の駅で電車を[降りて]ください。", "tip": "offは「はなれる」。乗り物からはなれる＝降りる。反対はget on ~（乗る）。車やタクシーから降りるときはget out of ~。"},
{"w": "hear about ~", "m": "〜について聞く", "s": ["〜のうわさを聞く"], "ex": "Did you [hear about] the new teacher?", "ft": "新しい先生のこと、[聞いた]？", "tip": "hear about ~「〜のこと（知らせ・うわさ）を聞く」。hear from ~ は「〜から連絡をもらう」で意味がちがうので注意。"},
{"w": "take out ~", "m": "〜を取り出す", "s": ["〜を外に出す", "〜を連れ出す"], "ex": "Ken [took out] his notebook in class.", "ft": "ケンは授業中にノートを[取り出した]。", "tip": "out＝外へ。中から外へ持っていく＝取り出す。take out the trash「ごみを出す」も出る。take - took - taken。"},
{"w": "go shopping", "m": "買い物に行く", "s": [], "ex": "Let's [go shopping] this Saturday.", "ft": "今週の土曜日に[買い物に行こう]。", "tip": "go ~ingで「〜しに行く」。場所はtoでなくatやinで、go shopping at the mallとする。go swimmingなども同じ形。"},
{"w": "be over", "m": "終わる", "s": ["終わっている"], "ex": "The movie [was over] at nine last night.", "ft": "昨夜、映画は9時に[終わった]。", "tip": "over＝すっかり終わって。School is over.「学校が終わった」の形で出る。= end, finish。be動詞は主語と時に合わせる。"},
{"w": "go on a trip", "m": "旅行に行く", "s": ["= take a trip"], "ex": "We will [go on a trip] to Kyoto.", "ft": "私たちは京都へ[旅行に行く]つもりだ。", "tip": "tripは「旅行」。行き先はtoで続ける。take a tripも同じ意味。school trip（修学旅行）もよく出る語。"},
{"w": "go out", "m": "外出する", "s": ["出かける"], "ex": "Let's [go out] for lunch today.", "ft": "今日は昼ごはんを食べに[出かけ]よう。", "tip": "outは「外へ」。go out for dinner（夕食を食べに出かける）の形が出る。反対はcome in（入る）やstay home（家にいる）。"},
{"w": "go back", "m": "戻る", "s": ["帰る"], "ex": "I have to [go back] to school.", "ft": "私は学校に[戻ら]なければならない。", "tip": "backは「元のところへ」。go back to ~（〜に戻る）の形。come back（戻ってくる）は話し手のところへ戻るときに使う。"},
{"w": "come back", "m": "戻ってくる", "s": ["帰ってくる"], "ex": "Please [come back] by six o'clock.", "ft": "6時までに[戻ってきて]ください。", "tip": "comeは話している人の方へ来る、goははなれて行く。come back home（家に帰ってくる）も出る。come - came - come。"},
{"w": "go away", "m": "立ち去る", "s": ["（痛みなどが）なくなる"], "ex": "The cat [went away] when I opened the door.", "ft": "ドアを開けると、ねこは[どこかへ行ってしまった]。", "tip": "away＝はなれて。その場からはなれていく＝立ち去る。Go away!「あっちへ行って」。come back（もどる）と反対。go - went - gone。"},
{"w": "come from ~", "m": "〜の出身である", "s": ["〜から来る"], "ex": "Emma [comes from] Australia, so she speaks English.", "ft": "エマはオーストラリア[出身な]ので英語を話す。", "tip": "Where do you come from?＝出身はどこですか。be from ~と同じ意味で、I come from Japan.＝I'm from Japan."},
{"w": "be busy with ~", "m": "〜で忙しい", "s": [], "ex": "I [am busy with] my homework today.", "ft": "今日は宿題[で忙しい]。", "tip": "with の後ろは名詞。be busy ~ing「〜するのに忙しい」もよく出る。busy の反対は free（ひまな）。"},
{"w": "put on ~", "m": "〜を着る", "s": ["〜をかぶる・はく", "〜を身につける"], "ex": "[Put on] your coat. It's cold.", "ft": "コートを[着なさい]。寒いよ。", "tip": "onは「くっつく」。体に服をくっつける＝着る。ぼうし・くつ・めがねにも使う。反対はtake off（脱ぐ）。put - put - put。"},
{"w": "take off ~", "m": "〜を脱ぐ", "s": ["（飛行機が）離陸する"], "ex": "Please [take off] your shoes here.", "ft": "ここでくつを[脱いで]ください。", "tip": "offは「はなれる」。体から服やくつをはなす＝脱ぐ。反対はput on（着る）。take - took - taken。"},
// ---- Day2 ----
{"w": "turn on ~", "m": "〜をつける", "s": ["（スイッチを）入れる"], "ex": "Can you [turn on] the light?", "ft": "電気を[つけて]くれる？", "tip": "onは「スイッチが入った状態」。テレビ・電気・ラジオに使う。反対はturn off（消す）。turn the light onの語順もある。"},
{"w": "turn off ~", "m": "〜を消す", "s": ["（スイッチを）切る"], "ex": "Please [turn] the TV [off].", "ft": "テレビを[消して]ください。", "tip": "offは「スイッチが切れた状態」。反対はturn on（つける）。turn the TV offのように間に名詞を入れてもよい。"},
{"w": "pick up ~", "m": "〜を拾い上げる", "s": ["〜を車で迎えに行く"], "ex": "Yuki [picked up] the pen on the floor.", "ft": "ユキは床のペンを[拾った]。", "tip": "up＝上へ。つまんで上げる＝拾う。pick me up「私を車で迎えに来る」も4級で出る。代名詞なら pick it up の語順。"},
{"w": "clean up ~", "m": "〜をきれいに片づける", "s": ["〜をすっかり掃除する"], "ex": "We [cleaned up] the classroom after school.", "ft": "放課後、私たちは教室を[きれいに片づけた]。", "tip": "up＝すっかり。clean（掃除する）に up がついて「すっかりきれいにする」。clean up the park「公園を片づける」の形でよく出る。"},
{"w": "wake up", "m": "目が覚める", "s": ["〜を起こす"], "ex": "I [woke up] at five this morning.", "ft": "私は今朝5時に[目が覚めた]。", "tip": "目が覚めるのがwake up、ベッドから出るのがget up。wake - woke - woken。wake me up（私を起こす）の形も出る。"},
{"w": "hurry up", "m": "急ぐ", "s": [], "ex": "[Hurry up], or you will be late.", "ft": "[急いで]、さもないと遅れるよ。", "tip": "命令文Hurry up!（急いで！）でよく使う。「命令文, or ~」は「さもないと〜」。in a hurryは「急いで」。"},
{"w": "grow up", "m": "成長する", "s": ["大人になる"], "ex": "I want to be a doctor when I [grow up].", "ft": "私は[大人になった]ら医者になりたい。", "tip": "growは「育つ」、upは「すっかり」。when I grow up（大人になったら）の形でよく出る。grow - grew - grown。"},
{"w": "give up", "m": "あきらめる", "s": ["〜をやめる"], "ex": "Don't [give up]. You can do it!", "ft": "[あきらめ]ないで。きみならできる！", "tip": "upは「すっかり」。すっかり手放す＝あきらめる。後ろに動詞を置くときはgive up ~ing。give - gave - given。"},
{"w": "come true", "m": "実現する", "s": ["（夢が）かなう"], "ex": "I hope your dream will [come true].", "ft": "あなたの夢が[かなう]といいね。", "tip": "trueは「本当の」。夢が本当になる＝かなう。主語はdream（夢）やwish（願い）が多い。過去形はcame true。"},
{"w": "get well", "m": "よくなる", "s": ["（病気が）治る"], "ex": "I hope you [get well] soon.", "ft": "早く[よくなる]といいね。", "tip": "getは「〜になる」、wellは「元気な」。お見舞いカードのGet well soon!（早くよくなってね）でよく出る。"},
{"w": "throw away ~", "m": "〜を捨てる", "s": [], "ex": "Don't [throw away] this box.", "ft": "この箱を[捨て]ないで。", "tip": "throwは「投げる」、awayは「遠くへ」。投げて遠ざける＝捨てる。throw - threw - thrown。ゴミの話でよく出る。"},
{"w": "write to ~", "m": "〜に手紙を書く", "s": ["〜にメールを書く"], "ex": "I [wrote to] my grandmother last week.", "ft": "私は先週、祖母に[手紙を書いた]。", "tip": "toは「〜へ」。手紙やメールをだれかへ書いて送る。write - wrote - written。hear from ~（〜から便りがある）とセットで覚える。"},
{"w": "hear from ~", "m": "〜から便りがある", "s": ["〜から連絡がある"], "ex": "I [heard from] Mike yesterday.", "ft": "きのう、マイク[から連絡があった]。", "tip": "fromは「〜から」。手紙・メール・電話をもらうこと。hear - heard - heard。hear of ~は「〜のうわさを聞く」で別の意味。"},
{"w": "help A with B", "m": "AのBを手伝う", "s": [], "ex": "Can you [help] me [with] my homework?", "ft": "私の宿題を[手伝って]くれる？", "tip": "help my homeworkとはしない。助ける相手を先に、手伝うことをwithの後ろに置く。help me cook（料理するのを手伝う）の形もある。"},
{"w": "thank A for B", "m": "BのことでAに感謝する", "s": ["BのことでAにお礼を言う"], "ex": "I [thanked] her [for] the nice gift.", "ft": "私はすてきなプレゼントのことで彼女に[お礼を言った]。", "tip": "forは「理由」。Thank you for ~.（〜をありがとう）の形でよく出る。forの後ろの動詞は~ingで、Thank you for coming."},
{"w": "arrive at ~", "m": "（場所）に到着する", "s": ["= get to ~"], "ex": "We [arrived at] the station at noon.", "ft": "私たちは正午に駅に[着いた]。", "tip": "せまい場所（駅・空港）はat、広い場所（国・都市）はinで、arrive in Tokyo。get to ~、reach ~と同じ意味。"},
{"w": "leave for ~", "m": "〜に向けて出発する", "s": [], "ex": "Ken will [leave for] London tomorrow.", "ft": "ケンは明日ロンドン[に向けて出発する]。", "tip": "forは「〜へ向かって」。leave Tokyo（東京を出発する）とleave for Tokyo（東京へ向かう）の区別に注意。leave - left - left。"},
{"w": "stay with ~", "m": "〜の家に泊まる", "s": ["〜といっしょにいる"], "ex": "I [stayed with] my uncle in Osaka.", "ft": "私は大阪のおじの[家に泊まった]。", "tip": "人の前はwith、場所の前はatやinで、stay at a hotel（ホテルに泊まる）。ホームステイの話でよく出る形。"},
{"w": "do the housework", "m": "家事をする", "s": [], "ex": "My father [does the housework] on Sundays.", "ft": "父は日曜日に[家事をする]。", "tip": "housework＝家の仕事（そうじ・洗たくなど）。do を使うのがポイント（make ではない）。do the dishes「皿洗いをする」も同じ形。"},
{"w": "think about ~", "m": "〜について考える", "s": ["= think of ~"], "ex": "I'm [thinking about] my summer plans.", "ft": "私は夏の計画[について考えて]いる。", "tip": "aboutは「〜について」。What do you think about ~?（〜をどう思う？）の形でよく出る。think - thought - thought。"},
{"w": "worry about ~", "m": "〜を心配する", "s": [], "ex": "Don't [worry about] the test.", "ft": "テストのことは[心配し]ないで。", "tip": "Don't worry.（心配しないで）は会話でよく出る。三人称単数はworries、過去形はworried。yをiに変えるつづりに注意。"},
{"w": "speak to ~", "m": "〜に話しかける", "s": ["〜と話す"], "ex": "A girl [spoke to] me at the park.", "ft": "公園で女の子が私に[話しかけた]。", "tip": "電話のMay I speak to Ken?（ケンさんをお願いします）でよく出る。speak - spoke - spoken。talk to ~とほぼ同じ。"},
{"w": "say hello to ~", "m": "〜によろしく伝える", "s": ["〜にあいさつする"], "ex": "Please [say hello to] your family.", "ft": "ご家族に[よろしく伝えて]ください。", "tip": "別れぎわにPlease say hello to ~.の形で使う。「〜にこんにちはと言う」から「よろしく」。say - said - said。"},
{"w": "have a good time", "m": "楽しい時を過ごす", "s": ["楽しむ", "= have fun"], "ex": "We [had a good time] at the party.", "ft": "私たちはパーティーで[楽しい時を過ごした]。", "tip": "goodの代わりにgreat・wonderfulも使う。have fun、enjoy myselfと同じ意味。過去形はhad a good time。"},
{"w": "have fun", "m": "楽しむ", "s": ["= have a good time"], "ex": "We [had fun] at the zoo yesterday.", "ft": "私たちはきのう動物園で[楽しんだ]。", "tip": "funは「楽しみ」で数えないのでaはつかない。Have fun!（楽しんでね）は見送りのことば。have fun ~ingで「〜して楽しむ」。"},
{"w": "have a cold", "m": "かぜをひいている", "s": [], "ex": "I [have a cold], so I'll stay home.", "ft": "[かぜをひいている]ので家にいるつもりだ。", "tip": "have a coldは「かぜをひいている状態」、catch a coldは「かぜをひく」動作。coldには「寒い」のほかに「かぜ」の意味がある。"},
{"w": "catch a cold", "m": "かぜをひく", "s": [], "ex": "Wear a coat, or you'll [catch a cold].", "ft": "コートを着なさい、さもないと[かぜをひく]よ。", "tip": "catchは「つかまえる」。かぜをつかまえる＝ひく。catch - caught - caught。have a cold（かぜをひいている）との区別が出る。"},
{"w": "have a headache", "m": "頭が痛い", "s": ["頭痛がする"], "ex": "I [have a headache] today.", "ft": "今日は[頭が痛い]。", "tip": "head（頭）＋ache（痛み）。stomachache（腹痛）、toothache（歯痛）も同じ形。aをつけてhaveを使う。"},
{"w": "make friends with ~", "m": "〜と友だちになる", "s": [], "ex": "I [made friends with] Emma at camp.", "ft": "私はキャンプでエマ[と友だちになった]。", "tip": "友だちになるには2人が必要なのでfriendsと複数形にする。make - made - made。become friendsも同じ意味。"},
{"w": "do one's homework", "m": "宿題をする", "s": [], "ex": "I [do my homework] after dinner.", "ft": "私は夕食後に[宿題をする]。", "tip": "one'sは主語に合わせてmy・his・herなどに変える。homeworkは数えない名詞なので、aやsはつけない。"},
// ---- Day3 ----
{"w": "do one's best", "m": "全力をつくす", "s": ["ベストをつくす"], "ex": "I will [do my best] in the game.", "ft": "私は試合で[全力をつくす]つもりだ。", "tip": "one'sは主語に合わせてmy・yourなどに。Do your best!（がんばって）は応援のことば。bestはgoodの最上級。"},
{"w": "be good at ~", "m": "〜が得意だ", "s": ["〜が上手だ"], "ex": "Yuki [is good at] playing the piano.", "ft": "ユキはピアノをひくのが[得意だ]。", "tip": "atの後ろは名詞か~ing。反対はbe bad at ~（〜が苦手）。good - better - best。be good at swimmingの形でよく出る。"},
{"w": "be interested in ~", "m": "〜に興味がある", "s": [], "ex": "I [am interested in] Japanese history.", "ft": "私は日本の歴史[に興味がある]。", "tip": "interested（興味をもった）は人が主語、interesting（おもしろい）は物が主語。inの後ろは名詞か~ing。"},
{"w": "be afraid of ~", "m": "〜をこわがる", "s": ["〜がこわい"], "ex": "My sister [is afraid of] big dogs.", "ft": "妹は大きな犬を[こわがっている]。", "tip": "ofの後ろは名詞か~ing。I'm afraid of the dark.（暗いのがこわい）。afraidは名詞の前に置かず、be afraidの形で使う。"},
{"w": "be late for ~", "m": "〜に遅れる", "s": ["〜に遅刻する"], "ex": "Don't [be late for] school.", "ft": "学校に[遅刻し]ないで。", "tip": "lateは「遅れた・遅い」。be late for school（学校に遅刻する）がよく出る。Don't be late.（遅れないで）も会話で出る。"},
{"w": "be famous for ~", "m": "〜で有名だ", "s": [], "ex": "This town [is famous for] its apples.", "ft": "この町はりんご[で有名だ]。", "tip": "forは「理由」で、有名な理由をforの後ろに置く。比較はfamous - more famous - most famous。"},
{"w": "be full of ~", "m": "〜でいっぱいだ", "s": [], "ex": "The park [was full of] children.", "ft": "公園は子どもたち[でいっぱいだった]。", "tip": "fullは「いっぱいの」。ofの後ろに中身を置く。I'm full.（おなかがいっぱい）も会話でよく出る。"},
{"w": "be ready for ~", "m": "〜の準備ができている", "s": [], "ex": "[Are] you [ready for] the test?", "ft": "テストの[準備はできている]？", "tip": "readyは「用意ができた」。後ろに動詞ならbe ready to do（〜する準備ができている）。Are you ready?（準備はいい？）もよく出る。"},
{"w": "be kind to ~", "m": "〜に親切だ", "s": ["〜にやさしい"], "ex": "Mike [is kind to] everyone in class.", "ft": "マイクはクラスのみんな[に親切だ]。", "tip": "toは「〜に対して」。kind - kinder - kindest。kindには「種類」の意味もあり、a kind of ~は「一種の〜」。"},
{"w": "be able to do", "m": "〜することができる", "s": ["= can"], "ex": "I [was able to] swim fast.", "ft": "私は速く泳ぐ[ことができた]。", "tip": "canと同じ意味で、toの後ろは動詞の原形。willとcanは並べられないので、未来はwill be able to ~、過去はwas able to ~。"},
{"w": "be going to do", "m": "〜するつもりだ", "s": ["〜しそうだ"], "ex": "I [am going to] visit Kyoto tomorrow.", "ft": "私は明日京都を訪ねる[つもりだ]。", "tip": "toの後ろは動詞の原形。前から決めていた予定に使う。willとの言いかえも出る。疑問文はAre you going to ~?"},
{"w": "have to do", "m": "〜しなければならない", "s": ["= must"], "ex": "I [have to] clean my room today.", "ft": "今日は部屋をそうじ[しなければならない]。", "tip": "mustと同じ意味。主語がheやsheならhas to、過去はhad to。don't have to ~は「〜しなくてよい」で、禁止ではない。"},
{"w": "want to do", "m": "〜したい", "s": [], "ex": "I [want to] go to Hawaii.", "ft": "私はハワイに行き[たい]。", "tip": "toの後ろは動詞の原形で、want ~ingとはしない。want to be ~で「〜になりたい」。would like to doはていねいな言い方。"},
{"w": "would like to do", "m": "〜したいのですが", "s": ["want to doのていねいな形"], "ex": "I [would like to] see the menu.", "ft": "メニューを見[たい]のですが。", "tip": "want toよりていねいな言い方で、I'd likeと短くする。Would you like to ~?は「〜しませんか」というさそい。"},
{"w": "decide to do", "m": "〜しようと決める", "s": [], "ex": "Ken [decided to] join the tennis club.", "ft": "ケンはテニス部に入る[ことに決めた]。", "tip": "toの後ろは動詞の原形で、decide ~ingとはしない。eで終わる語なので過去形はdecided。名詞形はdecision（決心）。"},
{"w": "try to do", "m": "〜しようとする", "s": [], "ex": "I [tried to] call you last night.", "ft": "ゆうべあなたに電話[しようとした]。", "tip": "toの後ろは動詞の原形。過去形はyをiに変えてtried。try ~ingは「試しに〜してみる」で意味が少しちがう。"},
{"w": "need to do", "m": "〜する必要がある", "s": [], "ex": "You [need to] bring your lunch tomorrow.", "ft": "明日はお弁当を持ってくる[必要がある]。", "tip": "toの後ろは動詞の原形。have to ~（〜しなければならない）に近い意味。don't need to ~は「〜する必要はない」。"},
{"w": "like ~ing", "m": "〜するのが好きだ", "s": ["= like to do"], "ex": "I [like reading] comic books.", "ft": "私はまんがを[読むのが好きだ]。", "tip": "like to doと同じ意味。ing形のつづりに注意：swim → swimming、dance → dancing。What do you like doing?も出る。"},
{"w": "enjoy ~ing", "m": "〜して楽しむ", "s": ["〜するのを楽しむ"], "ex": "We [enjoyed playing] soccer after school.", "ft": "私たちは放課後サッカーを[して楽しんだ]。", "tip": "enjoyの後ろは~ingで、enjoy to doとはしない。ここがテストでよく問われる。enjoy myself（楽しむ）の形もある。"},
{"w": "finish ~ing", "m": "〜し終える", "s": [], "ex": "I [finished doing] my homework at nine.", "ft": "私は9時に宿題を[し終えた]。", "tip": "finishの後ろは~ingで、finish to doとはしない。enjoy・stopも後ろは~ing。三人称単数はesをつけてfinishes。"},
{"w": "stop ~ing", "m": "〜するのをやめる", "s": [], "ex": "Please [stop talking] in the library.", "ft": "図書館で[話すのをやめて]ください。", "tip": "stopの後ろは~ingで「〜するのをやめる」。過去形・ing形はpを重ねてstopped・stopping。つづりに注意。"},
{"w": "start ~ing", "m": "〜し始める", "s": ["= start to do"], "ex": "It [started raining] in the afternoon.", "ft": "午後に雨が[降り始めた]。", "tip": "start to doと同じ意味。begin ~ing / begin to doも同じで、begin - began - begun。startは規則動詞でstarted。"},
{"w": "how to do", "m": "〜のしかた", "s": ["どうやって〜するか"], "ex": "Please tell me [how to] use this.", "ft": "これの使い[方]を教えてください。", "tip": "how to ~で「〜のしかた」。toの後ろは動詞の原形。what to do（何をすべきか）、where to go（どこへ行くべきか）も同じ形。"},
{"w": "a lot of ~", "m": "たくさんの〜", "s": ["= lots of ~"], "ex": "There are [a lot of] books here.", "ft": "ここには[たくさんの]本がある。", "tip": "数えられる名詞にも数えられない名詞にも使える。many（数）・much（量）の両方の代わりになる。lots of ~も同じ意味。"},
{"w": "lots of ~", "m": "たくさんの〜（くだけた形）", "s": ["= a lot of ~"], "ex": "We had [lots of] snow last winter.", "ft": "去年の冬は[たくさんの]雪が降った。", "tip": "a lot of ~と同じ意味で、少しくだけた言い方。lotsの前にaはつけない。数えられない名詞（snow・water）にも使える。"},
{"w": "a little ~", "m": "少しの〜（量）", "s": ["少し"], "ex": "I drink [a little] milk every morning.", "ft": "私は毎朝[少し]牛乳を飲む。", "tip": "数えられない名詞（milk・water・money）に使う。数えられる名詞にはa few。aがないlittleは「ほとんどない」。"},
{"w": "a few ~", "m": "2、3の〜（数）", "s": ["いくつかの〜"], "ex": "I have [a few] friends in Canada.", "ft": "私はカナダに[数人の]友だちがいる。", "tip": "数えられる名詞の複数形に使う：a few books。数えられない名詞にはa little。aがないfewは「ほとんどない」。"},
{"w": "a cup of ~", "m": "カップ1杯の〜", "s": [], "ex": "Would you like [a cup of] tea?", "ft": "紅茶を[1杯]いかがですか。", "tip": "温かい飲み物（tea・coffee）に使う。2杯はtwo cups of teaで、teaにsはつけない。冷たい飲み物はa glass of ~。"},
{"w": "write down ~", "m": "〜を書き留める", "s": ["〜をメモする"], "ex": "Please [write down] your name here.", "ft": "ここにあなたの名前を[書き留めて]ください。", "tip": "down＝紙の上に下ろす。聞いたことを紙に書いておく＝書き留める。write - wrote - written。代名詞なら write it down の語順。"},
{"w": "a piece of ~", "m": "1つの〜", "s": ["1切れの〜", "1枚の〜"], "ex": "Can I have [a piece of] cake?", "ft": "ケーキを[1切れ]もらえる？", "tip": "数えられない名詞を数えるときに使う：a piece of paper（紙1枚）、a piece of cake（ケーキ1切れ）。2つはtwo pieces of ~。"},
// ---- Day4 ----
{"w": "a kind of ~", "m": "一種の〜", "s": ["〜の一種"], "ex": "Sushi is [a kind of] Japanese food.", "ft": "すしは日本料理[の一種]だ。", "tip": "kindはここでは「種類」。What kind of ~?（どんな種類の〜）もよく出る。形容詞のkind（親切な）と区別する。"},
{"w": "share A with B", "m": "AをBと分け合う", "s": ["AをBといっしょに使う"], "ex": "I [share] my room [with] my brother.", "ft": "私は兄と部屋を[いっしょに使っている]。", "tip": "share＝分け合う・いっしょに使う。with の後ろは人。share the cookies with your sister「クッキーを妹と分ける」も出る。"},
{"w": "one of ~", "m": "〜のうちの1つ", "s": ["〜のうちの1人"], "ex": "Ken is [one of] my best friends.", "ft": "ケンは私の親友[の1人]だ。", "tip": "ofの後ろは必ず複数形：one of my friends。one of the most ~（最も〜なものの1つ）の形でもよく出る。"},
{"w": "a pair of ~", "m": "1組の〜", "s": ["1足の〜", "1本の〜"], "ex": "I bought [a pair of] shoes yesterday.", "ft": "私はきのう靴を[1足]買った。", "tip": "2つで1つになる物に使う。a pair of shoes（靴1足）、a pair of glasses（めがね1つ）。2つなら two pairs of ~ になる。"},
{"w": "all over the world", "m": "世界中で", "s": ["世界中の"], "ex": "People [all over the world] love soccer.", "ft": "[世界中の]人々がサッカーを愛している。", "tip": "all over＝〜のすみずみまで。all over Japan「日本中で」のように国の名前にも使える。around the world もほぼ同じ意味。"},
{"w": "say goodbye to ~", "m": "〜にさよならを言う", "s": ["〜に別れを告げる"], "ex": "Emma [said goodbye to] her friends at the station.", "ft": "エマは駅で友だちに[さよならを言った]。", "tip": "to の後ろは相手。say hello to ~「〜によろしくと言う」とセットで覚える。say - said - said、said の発音は /sed/。"},
{"w": "at the same time", "m": "同時に", "s": ["一度に"], "ex": "We arrived at school [at the same time].", "ft": "私たちは[同時に]学校に着いた。", "tip": "same＝同じ。the same time「同じ時」に at がつく。same の前にはいつも the がつく点に注意。"},
{"w": "for a while", "m": "しばらくの間", "s": [], "ex": "Let's rest here [for a while].", "ft": "ここで[しばらく]休もう。", "tip": "while＝少しの時間。for＋期間「〜の間」の形。wait for a while「しばらく待つ」でよく出る。for a long time は「長い間」。"},
{"w": "at first", "m": "最初は", "s": ["初めのうちは"], "ex": "[At first], I didn't like natto.", "ft": "[最初は]納豆が好きではなかった。", "tip": "「最初は〜だったが、あとで変わった」という話で使う。for the first time（初めて）と区別。at last（ついに）と対で覚える。"},
{"w": "at last", "m": "ついに", "s": ["= finally"], "ex": "[At last], we got to the top.", "ft": "[ついに]私たちは頂上に着いた。", "tip": "lastは「最後」。長く待ったあと最後に、という気持ち。finallyと同じ意味。at first（最初は）と対で覚える。"},
{"w": "for example", "m": "たとえば", "s": [], "ex": "I like fruit, [for example], apples and bananas.", "ft": "私は果物が好きだ。[たとえば]りんごやバナナだ。", "tip": "exampleは「例」。例をあげるときに使い、文の最初や途中に置く。前後にコンマをつけることが多い。"},
{"w": "for a long time", "m": "長い間", "s": [], "ex": "We talked [for a long time] last night.", "ft": "私たちはゆうべ[長い間]話した。", "tip": "forは「期間」を表す：for two hours（2時間）。How long ~?の答えでよく使う。a long time ago（ずっと前に）と区別。"},
{"w": "for the first time", "m": "初めて", "s": [], "ex": "I saw snow [for the first time].", "ft": "私は[初めて]雪を見た。", "tip": "firstは「最初の」。at first（最初は）との区別がよく出る。for the first time in my life（生まれて初めて）の形もある。"},
{"w": "in front of ~", "m": "〜の前で", "s": ["〜の前に"], "ex": "Let's meet [in front of] the station.", "ft": "駅の[前で]会おう。", "tip": "場所の「前」。反対はbehind ~（〜の後ろに）。時間の「前」はbefore。frontのつづり（oを使う）に注意。"},
{"w": "next to ~", "m": "〜のとなりに", "s": [], "ex": "The bank is [next to] the post office.", "ft": "銀行は郵便局の[となりに]ある。", "tip": "nextは「となりの・次の」。道案内の文でよく出る。near ~（〜の近くに）、between A and B（AとBの間に）とセットで覚える。"},
{"w": "have trouble with ~", "m": "〜で困っている", "s": ["〜に苦労する"], "ex": "Ken is [having trouble with] his computer.", "ft": "ケンはパソコンのことで[困っている]。", "tip": "trouble＝困ったこと。have trouble with ＋もの「〜で困る」。I'll help you with it.（手伝うよ）という返事とセットで出る。"},
{"w": "in the future", "m": "将来は", "s": ["未来に"], "ex": "I want to be a doctor [in the future].", "ft": "私は[将来]医者になりたい。", "tip": "future＝未来。in the past（過去に）と反対。I want to be ~ in the future.「将来〜になりたい」は作文でもよく使う。"},
{"w": "think of ~", "m": "〜をどう思う", "s": ["〜のことを考える", "〜を思いつく"], "ex": "What do you [think of] my new bag?", "ft": "私の新しいかばんを[どう思う]？", "tip": "What do you think of ~?「〜をどう思う？」の形でよく出る。think about ~ もほぼ同じ。think of a good idea「よい考えを思いつく」も。"},
{"w": "after school", "m": "放課後", "s": ["放課後に"], "ex": "We practice soccer [after school].", "ft": "私たちは[放課後]サッカーを練習する。", "tip": "afterは「〜のあとで」。schoolにtheはつけない。before school（授業の前）、after dinner（夕食後）も同じ形。"},
{"w": "on the way home", "m": "帰る途中で", "s": ["帰り道に"], "ex": "I met Yuki [on the way home].", "ft": "[帰る途中で]ユキに会った。", "tip": "wayは「道」。homeは副詞なのでtoはつけないが、学校ならon the way to school（学校へ行く途中で）とtoがいる。"},
{"w": "on foot", "m": "歩いて", "s": ["徒歩で"], "ex": "I go to school [on foot].", "ft": "私は[歩いて]学校へ行く。", "tip": "乗り物はbyだが、歩きだけはon foot。walk to schoolでも同じ意味。footの複数形はfeet。"},
{"w": "on time", "m": "時間どおりに", "s": ["遅れずに"], "ex": "The bus came [on time] this morning.", "ft": "今朝、バスは[時間どおりに]来た。", "tip": "on＝ぴったり。決められた時刻ぴったり＝時間どおり。in time「間に合って」とまぎらわしい。be late for ~（〜に遅れる）が反対。"},
{"w": "over there", "m": "あそこに", "s": ["向こうに"], "ex": "Look at the bird [over there].", "ft": "[あそこの]鳥を見て。", "tip": "thereだけでも「そこに」だが、over thereは少しはなれた「向こうのあそこ」。指さして言う場面でよく出る。"},
{"w": "right now", "m": "今すぐ", "s": ["ちょうど今"], "ex": "Please come to the kitchen [right now].", "ft": "[今すぐ]台所に来てください。", "tip": "rightは「ちょうど」でnowを強める。「今すぐ」と「ちょうど今」の2つの意味がある。right here（ちょうどここ）も同じ使い方。"},
{"w": "these days", "m": "このごろ", "s": ["最近"], "ex": "I'm very busy [these days].", "ft": "[このごろ]とても忙しい。", "tip": "theseはthisの複数形で「これらの日々」＝このごろ。現在形の文とよく使う。in those days（そのころ）と区別。"},
{"w": "one day", "m": "ある日", "s": [], "ex": "[One day], Ken found a small cat.", "ft": "[ある日]、ケンは小さなネコを見つけた。", "tip": "物語の始まりによく出る。過去の文なら「ある日」、未来の文なら「（いつか）ある日」の意味。someday（いつか）とセットで覚える。"},
{"w": "have a hard time", "m": "つらい思いをする", "s": ["苦労する"], "ex": "I [had a hard time] in the math test.", "ft": "数学のテストで[苦労した]。", "tip": "hard＝大変な。have a good time「楽しく過ごす」の反対の言い方。have - had - had と過去形で使うことが多い。"},
{"w": "be born", "m": "生まれる", "s": [], "ex": "My sister [was born] in May.", "ft": "妹は5月に[生まれた]。", "tip": "生まれた日や年を言うときは was / were born の形。in＋月・年、on＋日付とセット。I was born in 2012. のように使う。"},
{"w": "a long time ago", "m": "ずっと前に", "s": ["昔"], "ex": "People lived here [a long time ago].", "ft": "[ずっと前に]人々がここに住んでいた。", "tip": "agoは「〜前に」で過去形の文に使う：two years ago（2年前）。for a long time（長い間）と区別する。"},
{"w": "each other", "m": "おたがい", "s": ["たがいに"], "ex": "Ken and Mike help [each other].", "ft": "ケンとマイクは[おたがいに]助け合う。", "tip": "2人以上がたがいに〜する。名詞の働きなので、前置詞が必要なときはtalk with each otherのようにwithなどを入れる。"},
// ---- Day5 ----
{"w": "far from ~", "m": "〜から遠い", "s": [], "ex": "My house is [far from] the station.", "ft": "私の家は駅[から遠い]。", "tip": "farは「遠い」。反対はnear（近い）。How far ~?（どのくらい遠い）で距離をたずねる。far - farther - farthest。"},
{"w": "from A to B", "m": "AからBまで", "s": [], "ex": "The shop is open [from] ten [to] seven.", "ft": "その店は[10時から7時まで]開いている。", "tip": "時間にも場所にも使う：from Monday to Friday（月曜から金曜まで）。from Tokyo to Osaka（東京から大阪まで）も出る。"},
{"w": "between A and B", "m": "AとBの間に", "s": [], "ex": "The bank is [between] the park [and] the school.", "ft": "銀行は[公園と学校の間に]ある。", "tip": "betweenは2つの間。3つ以上の間はamong。道案内でよく出る。between ten and elevenのように時間にも使う。"},
{"w": "both A and B", "m": "AもBも両方", "s": [], "ex": "I like [both] dogs [and] cats.", "ft": "私は[犬もネコも]好きだ。", "tip": "主語に使うと複数あつかいなので、Both Ken and Yuki are ~とareになる。bothだけで「両方」の意味もある。"},
{"w": "not ~ at all", "m": "まったく〜ない", "s": ["少しも〜ない"], "ex": "I'm [not] tired [at all].", "ft": "私は[まったく]つかれていない。", "tip": "notの意味を強める。Not at all.は「どういたしまして」の意味でも使う。会話文の答えとして出ることがある。"},
{"w": "more than ~", "m": "〜より多い", "s": ["〜以上"], "ex": "[More than] thirty students came to the party.", "ft": "30人[より多くの]生徒がパーティーに来た。", "tip": "moreはmanyとmuchの比較級。比較の文A is more ~ than B.とも合わせて覚える。thanの後ろに数が来ることが多い。"},
{"w": "How about ~?", "m": "〜はどうですか", "s": ["〜はいかがですか"], "ex": "[How about] going to the zoo tomorrow?", "ft": "明日、動物園に行くの[はどう]？", "tip": "さそいや提案に使う。後ろは名詞か~ing。How about you?（あなたはどう？）もよく出る。答えはThat's a good idea.など。"},
{"w": "Why don't we ~?", "m": "〜しませんか", "s": ["= Let's ~."], "ex": "[Why don't we] have lunch together?", "ft": "いっしょに昼食を食べ[ませんか]。", "tip": "直訳は「なぜ〜しないの？」だが、さそいの表現。後ろは動詞の原形。Let's ~.と同じ意味。Why don't you ~?は「〜したらどう？」。"},
{"w": "Shall I ~?", "m": "（私が）〜しましょうか", "s": [], "ex": "[Shall I] open the window?", "ft": "窓を開け[ましょうか]。", "tip": "相手のために何かを申し出る表現。答えはYes, please.かNo, thank you.。Shall we ~?（いっしょに〜しましょうか）と区別。"},
{"w": "Shall we ~?", "m": "（いっしょに）〜しましょうか", "s": ["= Let's ~."], "ex": "[Shall we] go to the park after lunch?", "ft": "昼食のあと公園に行き[ましょうか]。", "tip": "Let's ~.と同じさそいの表現。答えはYes, let's.かNo, let's not.。Shall I ~?（私が〜しましょうか）と区別。"},
{"w": "Will you ~?", "m": "〜してくれませんか", "s": ["〜するつもりですか"], "ex": "[Will you] close the door, please?", "ft": "ドアを閉めて[くれませんか]。", "tip": "たのみごとの表現で、後ろは動詞の原形。Can you ~?と近い意味。答えはSure.やAll right.。「〜するつもり？」の意味もある。"},
{"w": "Could you ~?", "m": "〜していただけますか", "s": ["〜してくれませんか"], "ex": "[Could you] open the window, please?", "ft": "窓を開けて[いただけますか]。", "tip": "Can you ~? よりていねいな頼み方。後ろは動詞の原形。答え方は Sure. / OK. / Sorry, I can't. がよく出る。"},
{"w": "be happy to do", "m": "喜んで〜する", "s": ["〜してうれしい"], "ex": "I [am happy to] carry your bag.", "ft": "[喜んで]あなたのかばんを運びます。", "tip": "to の後ろは動詞の原形。I'm happy to help.「喜んで手伝うよ」。I'm happy to see you.「会えてうれしい」の意味もある。glad も同じ。"},
{"w": "Would you like ~?", "m": "〜はいかがですか", "s": ["Would you like to ~?＝〜しませんか"], "ex": "[Would you like] some cake?", "ft": "ケーキ[はいかがですか]。", "tip": "ものをすすめるていねいな表現。後ろにto doが来ると「〜しませんか」。答えはYes, please.かNo, thank you.。"},
{"w": "How much ~?", "m": "〜はいくらですか", "s": ["どのくらいの量の〜"], "ex": "[How much] is this T-shirt?", "ft": "このTシャツ[はいくらですか]。", "tip": "値段や量をたずねる。How many ~?は数をたずね、後ろは複数形。買い物の会話でよく出る。答えはIt's 1,000 yen.など。"},
{"w": "How long ~?", "m": "どのくらい長く〜", "s": ["どのくらいの長さ"], "ex": "[How long] did you stay in Kyoto?", "ft": "京都に[どのくらい]いたのですか。", "tip": "期間や物の長さをたずねる。答えはFor three days.（3日間）など。How far（距離）、How often（回数）と区別。"},
{"w": "How often ~?", "m": "どのくらいよく〜", "s": ["何回〜"], "ex": "[How often] do you play tennis?", "ft": "[どれくらいよく]テニスをするの？", "tip": "回数・頻度をたずねる。答えはOnce a week.（週に1回）やEvery day.など。oftenは「よく・しばしば」。"},
{"w": "What's wrong?", "m": "どうしたの？", "s": ["= What's the matter?"], "ex": "[What's wrong]? You look sad.", "ft": "[どうしたの]？悲しそうだね。", "tip": "相手のようすが変なときに使う。What's the matter?と同じ。答えはI have a headache.など。wrongは「悪い・まちがった」。"},
{"w": "That's too bad.", "m": "それはお気の毒に。", "s": ["それは残念だね。"], "ex": "You have a cold? [That's too bad].", "ft": "かぜをひいているの？[それはお気の毒に]。", "tip": "相手の悪い知らせに返すことば。I'm sorry to hear that.も近い意味。会話の応答問題でよく出る。"},
{"w": "go abroad", "m": "外国へ行く", "s": ["海外に行く"], "ex": "My uncle will [go abroad] next month.", "ft": "おじは来月[外国へ行きます]。", "tip": "abroad は「外国へ」という意味の副詞なので to はつけない。go to abroad はまちがい。study abroad「留学する」も覚えておく。"},
{"w": "Sounds good.", "m": "いいね。", "s": ["それはよさそうだね。"], "ex": "[Sounds good]. Let's go to the park.", "ft": "[いいね]。公園に行こう。", "tip": "That sounds good.の短い形。提案に賛成するときの返事。Sounds great.やSounds fun.も同じ形。soundは「〜に聞こえる」。"},
{"w": "Good idea.", "m": "いい考えだね。", "s": ["= That's a good idea."], "ex": "[Good idea]. Let's ask Emma, too.", "ft": "[いい考えだね]。エマにも聞いてみよう。", "tip": "That's a good idea.の短い形。How about ~?やShall we ~?への返事でよく出る。ideaの発音は「アイディーア」。"},
{"w": "No problem.", "m": "いいですよ。", "s": ["どういたしまして。"], "ex": "[No problem]. I'll help you.", "ft": "[いいよ]。手伝ってあげる。", "tip": "たのみごとへの「いいよ」、お礼への「どういたしまして」の両方に使う。problemは「問題」。Sure.やOK.と近い。"},
{"w": "Hold on.", "m": "（電話で）少し待って", "s": ["ちょっと待って"], "ex": "[Hold on], please. I'll get my mother.", "ft": "[少々お待ちください]。母を呼んできます。", "tip": "電話の会話でよく出る。hold＝持つ、on＝そのまま続けて。電話を切らずに持っていて＝待って。Just a minute. も同じ意味。"},
{"w": "Just a minute.", "m": "ちょっと待って。", "s": ["= Wait a minute.", "= Just a moment."], "ex": "[Just a minute]. I'll get my bag.", "ft": "[ちょっと待って]。かばんを取ってくる。", "tip": "minuteは「分」で、「1分だけ」→ちょっと待って。Just a moment.やWait a minute.も同じ意味。電話の会話でもよく出る。"},
{"w": "What's the matter?", "m": "どうかしたの？", "s": ["何か困ったことがあるの？"], "ex": "[What's the matter]? You look sad.", "ft": "[どうしたの]？悲しそうだね。", "tip": "matter＝問題。元気がない人に声をかける言い方。What's wrong? も同じ意味。答えは I have a cold. などがよく出る。"},
{"w": "Go ahead.", "m": "どうぞ", "s": ["お先にどうぞ", "さあ、やって"], "ex": "[Go ahead] and eat the cake, Ken.", "ft": "ケン、[どうぞ]ケーキを食べて。", "tip": "ahead＝前へ。「前に進んで」から「どうぞ」。May I ~? と聞かれて OK するときによく使う。Sure. や Of course. と同じ働き。"},
{"w": "Why not?", "m": "もちろん、いいよ", "s": ["どうしてだめなの？"], "ex": "Ken said, \"Let's play tennis.\" I said, \"[Why not]?\"", "ft": "ケンが「テニスをしよう」と言った。私は「[もちろん、いいよ]」と言った。", "tip": "誘われて「もちろん、いいよ」と答える言い方。Let's ~. / Shall we ~? への返事で出る。否定文の後なら「どうしてだめなの？」の意味。"},
{"w": "the other day", "m": "先日", "s": ["この間"], "ex": "I met Mike at the library [the other day].", "ft": "[先日]図書館でマイクに会った。", "tip": "other＝ほかの。過去のある日を指すので、動詞はいつも過去形。the next day（次の日）と区別。meet - met - met。"},
{"w": "Good for you.", "m": "よかったね", "s": ["よくやったね"], "ex": "You won the game? [Good for you]!", "ft": "試合に勝ったの？[よかったね]！", "tip": "相手によいことがあったときにかける言葉。「あなたのためによい」と訳さない。That's too bad.「それは残念だね」と反対の場面で使う。"},
];
