// 英検5級 英熟語・表現 100
// 並び順＝学習順（25個ずつ Day1〜4）。ex/ft の [ ] が熟語とその訳
window.EIKEN_IDIOMS = [
// ---- Day1 ----
{"w": "get up", "m": "起きる", "s": ["立ち上がる"], "ex": "I [get up] at six every day.", "ft": "私は毎日6時に[起きる]。", "tip": "wake up は「目がさめる」、get up は「ふとんから出て起きる」。What time do you get up? の質問でよく出る。"},
{"w": "go to bed", "m": "寝る", "s": ["ベッドに入る"], "ex": "I [go to bed] at nine.", "ft": "私は9時に[寝る]。", "tip": "bed の前に a や the をつけない。反対は get up。go to bed は「ねどこに入る」、sleep は「ねむる」。"},
{"w": "go to school", "m": "学校へ行く", "s": ["通学する"], "ex": "I [go to school] by bike.", "ft": "私は自転車で[学校へ行く]。", "tip": "school の前に a や the をつけない。by bus（バスで）や on foot（歩いて）とセットでよく出る。"},
{"w": "go home", "m": "家に帰る", "s": [], "ex": "Let's [go home] now.", "ft": "もう[家に帰ろう]。", "tip": "home の前に to をつけない（go to home は×）。home だけで「家へ」の意味があるから。"},
{"w": "come home", "m": "帰宅する", "s": ["家に帰ってくる"], "ex": "My father [comes home] at seven.", "ft": "父は7時に[帰ってくる]。", "tip": "go home と同じく to はいらない。家で待つ人から見ると come home、出かけた先から帰るのが go home。"},
{"w": "look at ~", "m": "〜を見る", "s": ["〜をながめる"], "ex": "[Look at] this picture.", "ft": "この写真を[見て]。", "tip": "at は「1つの点」。1つのものに目を向けるときに使う。テレビやスポーツなど動くものを見るのは watch。"},
{"w": "listen to ~", "m": "〜を聞く", "s": ["〜に耳をかたむける"], "ex": "I [listen to] music in my room.", "ft": "私は部屋で音楽を[聞く]。", "tip": "to を忘れやすい。listen to music の形でよく出る。自然に耳に入ってくるのは hear で区別する。"},
{"w": "wait for ~", "m": "〜を待つ", "s": [], "ex": "I am [waiting for] my friend.", "ft": "私は友だちを[待っている]。", "tip": "for は「〜のために」。wait だけだと「待つ」。Wait a minute.（ちょっと待って）もよく出る形。"},
{"w": "talk with ~", "m": "〜と話す", "s": ["= talk to ~"], "ex": "I often [talk with] my sister.", "ft": "私はよく姉と[話す]。", "tip": "with は「〜といっしょに」。だれと話すかは with、何について話すかは about で表す。"},
{"w": "talk about ~", "m": "〜について話す", "s": [], "ex": "We [talk about] our favorite games.", "ft": "私たちは好きなゲーム[について話す]。", "tip": "about は「〜について」。talk with Ken about soccer（ケンとサッカーについて話す）のように並べても使う。"},
{"w": "sit down", "m": "すわる", "s": ["着席する"], "ex": "Please [sit down] here.", "ft": "ここに[すわって]ください。", "tip": "反対は stand up（立つ）。先生が教室で言う Sit down, please. の形でよく出る。down は「下へ」。"},
{"w": "stand up", "m": "立ち上がる", "s": ["立つ"], "ex": "Please [stand up], Ken.", "ft": "ケン、[立って]ください。", "tip": "up は「上へ」、down は「下へ」。stand up と sit down はセットで覚えたい。教室の指示でよく出る。"},
{"w": "come in", "m": "入る", "s": ["中に入る"], "ex": "Please [come in] and sit down.", "ft": "どうぞ[入って]、すわってください。", "tip": "in は「中へ」。ドアをノックされたときの Come in.（どうぞ入って）でよく出る。反対は go out。"},
{"w": "come back", "m": "もどる", "s": ["帰ってくる"], "ex": "Please [come back] by five.", "ft": "5時までに[もどって]ください。", "tip": "back は「もとの場所へ」。come back home（家に帰ってくる）や come back to school の形も出る。"},
{"w": "go out", "m": "外出する", "s": ["外に出る"], "ex": "Let's [go out] and play.", "ft": "[外に出て]遊ぼう。", "tip": "out は「外へ」。反対は come in（入る）。go out for dinner（夕食を食べに出かける）も出る。"},
{"w": "go shopping", "m": "買い物に行く", "s": [], "ex": "I [go shopping] with my mother.", "ft": "私は母と[買い物に行く]。", "tip": "go ~ing で「〜しに行く」。場所は to ではなく at や in を使う。go shopping at the mall の形。"},
{"w": "go fishing", "m": "つりに行く", "s": [], "ex": "We often [go fishing] in the river.", "ft": "私たちはよく川へ[つりに行く]。", "tip": "go ~ing の仲間。場所の前は to ではなく in を使う。go fishing in the sea（海につりに行く）の形。"},
{"w": "go swimming", "m": "泳ぎに行く", "s": [], "ex": "Let's [go swimming] this afternoon.", "ft": "今日の午後、[泳ぎに行こう]。", "tip": "swim の m を重ねて swimming になる。つづりの注意。go swimming in the sea（海に泳ぎに行く）の形で出る。"},
{"w": "go camping", "m": "キャンプに行く", "s": [], "ex": "We [go camping] every summer.", "ft": "私たちは毎年夏に[キャンプに行く]。", "tip": "go ~ing の仲間で、go shopping・go fishing といっしょに覚える。to をつけないのがポイント。"},
{"w": "take a picture", "m": "写真をとる", "s": ["= take a photo"], "ex": "Can I [take a picture] here?", "ft": "ここで[写真をとっても]いいですか。", "tip": "「とる」は take を使う。take pictures of flowers（花の写真をとる）のように of の後ろに写すものを置く。"},
{"w": "take a bath", "m": "ふろに入る", "s": [], "ex": "I [take a bath] after dinner.", "ft": "私は夕食のあとに[ふろに入る]。", "tip": "「入る」なのに enter ではなく take を使う。take a shower（シャワーをあびる）とセットで覚える。"},
{"w": "take a shower", "m": "シャワーをあびる", "s": [], "ex": "I [take a shower] in the morning.", "ft": "私は朝に[シャワーをあびる]。", "tip": "take a bath と同じ形。a を忘れないこと。shower の発音は「シャウア」に近い。"},
{"w": "have breakfast", "m": "朝食を食べる", "s": ["= eat breakfast"], "ex": "I [have breakfast] at seven.", "ft": "私は7時に[朝食を食べる]。", "tip": "breakfast の前に a や the をつけない。lunch（昼食）、dinner（夕食）も同じく have lunch の形。"},
{"w": "have a good time", "m": "楽しい時を過ごす", "s": ["楽しむ"], "ex": "I always [have a good time] with my friends.", "ft": "友だちといると、いつも[楽しい時間を過ごせる]。", "tip": "good の代わりに great もある。Have a good time!（楽しんできてね）と出かける人に言う形も出る。"},
{"w": "play the piano", "m": "ピアノをひく", "s": [], "ex": "My sister [plays the piano] well.", "ft": "姉は[ピアノをひく]のが上手だ。", "tip": "楽器には the をつける（play the guitar）。スポーツは the なし（play tennis）。この区別がよく出る。"},
// ---- Day2 ----
{"w": "do one's homework", "m": "宿題をする", "s": [], "ex": "I [do my homework] after dinner.", "ft": "私は夕食のあとに[宿題をする]。", "tip": "one's は my・your・his などに変わる。He does his homework. のように主語に合わせる。homework に s はつかない。"},
{"w": "watch TV", "m": "テレビを見る", "s": [], "ex": "I [watch TV] after school.", "ft": "私は放課後に[テレビを見る]。", "tip": "TV の前に the をつけない。動くものをじっと見るのが watch。写真や絵を見るのは look at。"},
{"w": "wash the dishes", "m": "皿をあらう", "s": ["食器をあらう"], "ex": "I often [wash the dishes] for my mother.", "ft": "私はよく母のために[皿をあらう]。", "tip": "dish は「皿」、複数は es をつけて dishes。家の手伝いの話でよく出る。cook dinner（夕食を作る）も仲間。"},
{"w": "live in ~", "m": "〜に住んでいる", "s": [], "ex": "My uncle [lives in] Tokyo.", "ft": "おじは東京に[住んでいる]。", "tip": "in は「〜の中に」。町や国の名前の前に置く。Where do you live?（どこに住んでいますか）の答えで出る。"},
{"w": "be from ~", "m": "〜の出身だ", "s": ["〜から来ている"], "ex": "My teacher [is from] Canada.", "ft": "私の先生はカナダ[出身だ]。", "tip": "from は「〜から」。Where are you from?（どこの出身ですか）→ I'm from Japan. の形でよく出る。"},
{"w": "be good at ~", "m": "〜が得意だ", "s": ["〜が上手だ"], "ex": "Yumi [is good at] tennis.", "ft": "ユミはテニスが[得意だ]。", "tip": "at の後ろは名詞か ~ing。be good at swimming（泳ぐのが得意）の形も出る。反対は be not good at ~。"},
{"w": "be late for ~", "m": "〜に遅れる", "s": ["〜に遅刻する"], "ex": "Don't [be late for] school.", "ft": "学校に[遅れて]はいけません。", "tip": "late は「遅れた」。for の後ろに school や the bus など遅れるものを置く。Don't be late. の形も出る。"},
{"w": "like ~ing", "m": "〜するのが好きだ", "s": ["= like to do"], "ex": "I [like reading] books.", "ft": "私は本を[読むのが好きだ]。", "tip": "like の後ろに動詞を置くときは ~ing の形にする。like to read と同じ意味。swim→swimming のつづりに注意。"},
{"w": "want to do", "m": "〜したい", "s": [], "ex": "I [want to play] soccer.", "ft": "私はサッカーを[したい]。", "tip": "want は「ほしい」。want to の後ろは動詞のもとの形。What do you want to be?（何になりたい？）もよく出る。"},
{"w": "like to do", "m": "〜するのが好きだ", "s": ["= like ~ing"], "ex": "My brother [likes to draw] pictures.", "ft": "弟は絵を[かくのが好きだ]。", "tip": "to の後ろは動詞のもとの形。like ~ing と同じ意味で、どちらもよく出る。主語が he なら likes になる。"},
{"w": "Let's ~.", "m": "〜しよう", "s": [], "ex": "[Let's] play soccer together.", "ft": "いっしょにサッカーを[しよう]。", "tip": "Let's の後ろは動詞のもとの形。答え方は Yes, let's.（うん、そうしよう）や OK. の形がよく出る。"},
{"w": "help A with B", "m": "AのBを手伝う", "s": [], "ex": "I [help] my mother [with] the cooking.", "ft": "私は母の料理を[手伝う]。", "tip": "A には人、B には仕事を入れる。help my homework は×。手伝う相手の人を先に置くのがポイント。"},
{"w": "look for ~", "m": "〜をさがす", "s": [], "ex": "I am [looking for] my pencil case.", "ft": "私は筆箱を[さがしている]。", "tip": "for は「〜を求めて」。さがしている途中が look for、見つけたら find。look at（〜を見る）とまちがえやすい。"},
{"w": "put on ~", "m": "〜を着る", "s": ["〜をかぶる・はく"], "ex": "[Put on] your jacket. It's cold today.", "ft": "上着を[着なさい]。今日は寒いよ。", "tip": "服・ぼうし・くつなど身につけるもの全部に使える。反対は take off（ぬぐ）。put your coat on の形もある。"},
{"w": "wake up", "m": "目がさめる", "s": ["〜を起こす"], "ex": "I [wake up] at six thirty.", "ft": "私は6時半に[目がさめる]。", "tip": "wake up は目をあけること、get up はふとんから出ること。Wake up!（起きて！）の形でもよく出る。"},
{"w": "at home", "m": "家で", "s": ["家に"], "ex": "I study [at home] on Sundays.", "ft": "日曜日は[家で]勉強する。", "tip": "at は「点」で場所をしめす。stay at home（家にいる）の形でよく出る。go home には at をつけない。"},
{"w": "at school", "m": "学校で", "s": [], "ex": "I eat lunch [at school].", "ft": "私は[学校で]昼ご飯を食べる。", "tip": "school の前に the をつけない。at home と同じ形。Ken is at school.（ケンは学校にいる）の形も出る。"},
{"w": "at night", "m": "夜に", "s": [], "ex": "I read books [at night].", "ft": "私は[夜に]本を読む。", "tip": "night は at、morning・afternoon・evening は in the を使う。この区別がよく出る。the もつけない。"},
{"w": "in the morning", "m": "朝に", "s": ["午前中に"], "ex": "I walk my dog [in the morning].", "ft": "私は[朝に]犬の散歩をする。", "tip": "朝・午後・夕方は in the。夜だけ at night。on Sunday morning のように曜日がつくと on になる。"},
{"w": "in the afternoon", "m": "午後に", "s": [], "ex": "We play soccer [in the afternoon].", "ft": "私たちは[午後に]サッカーをする。", "tip": "after（あと）＋noon（正午）で「正午のあと＝午後」。in the を忘れないこと。朝は in the morning。"},
{"w": "in the evening", "m": "夕方に", "s": ["晩に"], "ex": "I watch TV [in the evening].", "ft": "私は[夕方に]テレビを見る。", "tip": "evening は夕方から寝るまでの時間。夜おそくは at night。Good evening.（こんばんは）も同じ語。"},
{"w": "on Sunday", "m": "日曜日に", "s": [], "ex": "I play baseball [on Sunday].", "ft": "私は[日曜日に]野球をする。", "tip": "曜日の前は on。on Sundays と s をつけると「毎週日曜日に」。曜日は大文字で書き始める。"},
{"w": "every day", "m": "毎日", "s": [], "ex": "I practice the piano [every day].", "ft": "私は[毎日]ピアノの練習をする。", "tip": "day に s はつけない。every の後ろは1つの形。every morning（毎朝）、every week（毎週）も同じ仲間。"},
{"w": "after school", "m": "放課後", "s": ["学校のあとで"], "ex": "I go to the library [after school].", "ft": "私は[放課後]図書館へ行く。", "tip": "after は「〜のあと」。school の前に the はいらない。before school（学校の前に）は反対の言い方。"},
{"w": "before dinner", "m": "夕食の前に", "s": [], "ex": "I do my homework [before dinner].", "ft": "私は[夕食の前に]宿題をする。", "tip": "before は「〜の前に」、反対は after。Wash your hands before dinner. のように手洗いの話でも出る。"},
// ---- Day3 ----
{"w": "a lot of ~", "m": "たくさんの〜", "s": ["= lots of ~"], "ex": "Ken has [a lot of] comic books.", "ft": "ケンは[たくさんの]まんがを持っている。", "tip": "数えられるもの（books）にも数えられないもの（water）にも使える。lots of ~ と同じ意味。"},
{"w": "a little", "m": "少し", "s": ["少しの〜"], "ex": "I can speak English [a little].", "ft": "私は英語を[少し]話せる。", "tip": "a little は「少し」。a little water のように後ろに名詞を置くと「少しの〜」。a little bit も同じ意味。"},
{"w": "a cup of ~", "m": "カップ1杯の〜", "s": [], "ex": "I drink [a cup of] tea every morning.", "ft": "私は毎朝[1杯の]紅茶を飲む。", "tip": "あたたかい飲み物は cup、冷たい飲み物は glass。2杯なら two cups of tea と cup に s をつける。"},
{"w": "a glass of ~", "m": "コップ1杯の〜", "s": [], "ex": "Can I have [a glass of] water?", "ft": "水を[コップ1杯]もらえますか。", "tip": "冷たい水やジュース、牛乳は glass。あたたかいお茶は cup。2杯は two glasses of と es をつける。"},
{"w": "lots of ~", "m": "たくさんの〜", "s": ["= a lot of ~"], "ex": "There are [lots of] flowers in the park.", "ft": "公園には[たくさんの]花がある。", "tip": "a lot of と同じ意味。lots の s を忘れないこと。会話でよく使う、くだけた言い方。"},
{"w": "all day", "m": "一日中", "s": [], "ex": "We play games [all day] on Sunday.", "ft": "日曜日は[一日中]ゲームをする。", "tip": "all は「全部」。the をつけない。all night（一晩中）、all year（一年中）も同じ仲間。"},
{"w": "over there", "m": "あそこに", "s": ["向こうに"], "ex": "My house is [over there].", "ft": "私の家は[あそこ]だ。", "tip": "here（ここ）の反対が there（そこ）。over がつくと少しはなれた「あそこ・向こう」になる。指さしながら使う。"},
{"w": "right now", "m": "今すぐ", "s": ["ちょうど今"], "ex": "Please come here [right now].", "ft": "[今すぐ]ここに来てください。", "tip": "right は「ちょうど」。now を強めた言い方。I'm busy right now.（今いそがしい）のように「ちょうど今」の意味もある。"},
{"w": "next to ~", "m": "〜のとなりに", "s": [], "ex": "My school is [next to] the park.", "ft": "私の学校は公園の[となりに]ある。", "tip": "next は「となりの・次の」。Where is ~? の答えでよく出る。near（近くに）より、ぴったりとなりの感じ。"},
{"w": "in front of ~", "m": "〜の前に", "s": [], "ex": "Let's meet [in front of] the station.", "ft": "駅の[前で]会おう。", "tip": "of を忘れないこと。反対は behind（〜のうしろに）。時間の「前」は before、場所の「前」が in front of。"},
{"w": "by bus", "m": "バスで", "s": [], "ex": "My sister goes to school [by bus].", "ft": "姉は[バスで]学校へ行く。", "tip": "乗り物の前に by を置き、a や the はつけない。by train・by bike も同じ。歩いては on foot。"},
{"w": "from A to B", "m": "AからBまで", "s": [], "ex": "I study [from] seven [to] eight.", "ft": "私は[7時から8時まで]勉強する。", "tip": "時間にも場所にも使える。from Monday to Friday（月曜から金曜まで）の形でよく出る。"},
{"w": "very much", "m": "とても", "s": ["たいへん"], "ex": "I like dogs [very much].", "ft": "私は犬が[とても]好きだ。", "tip": "文の最後に置くのがポイント。Thank you very much. の形でもよく出る。I very like ~ は×。"},
{"w": "last night", "m": "昨夜", "s": ["きのうの夜"], "ex": "I watched a movie [last night].", "ft": "私は[昨夜]映画を見た。", "tip": "last は「この前の」。last Sunday（この前の日曜日）も同じ。文は過去の形になる。tonight（今夜）とまちがえないこと。"},
{"w": "this weekend", "m": "今週末", "s": [], "ex": "Let's go camping [this weekend].", "ft": "[今週末]キャンプに行こう。", "tip": "weekend は土曜日と日曜日のこと。this の前に on や in はつけない。next weekend（来週末）も出る。"},
{"w": "How about ~?", "m": "〜はどうですか", "s": ["〜はいかが"], "ex": "I like red. [How about] you?", "ft": "私は赤が好き。あなた[はどう]？", "tip": "相手に意見を聞いたり、すすめたりする。How about this one?（これはどう？）。後ろに動詞なら ~ing の形。"},
{"w": "What time ~?", "m": "何時に〜", "s": ["何時"], "ex": "[What time] do you get up?", "ft": "あなたは[何時に]起きますか。", "tip": "答えは時こくで、At six.（6時に）や It's seven.（7時です）。What time is it?（今何時？）もよく出る。"},
{"w": "How many ~?", "m": "いくつの〜", "s": ["何人の〜"], "ex": "[How many] cats do you have?", "ft": "ねこを[何びき]飼っていますか。", "tip": "数をたずねる。後ろの名詞は cats のように s がつく形。ねだんを聞くのは How much。答えは I have two. の形。"},
{"w": "How much ~?", "m": "〜はいくらですか", "s": ["どれくらいの量"], "ex": "[How much] is this T-shirt?", "ft": "このTシャツは[いくらですか]。", "tip": "ねだんをたずねる。答えは It's 500 yen. の形。数を聞く How many とまちがえやすいので注意。"},
{"w": "How old ~?", "m": "何歳〜", "s": ["どれくらい古い"], "ex": "[How old] is your brother?", "ft": "あなたのお兄さんは[何歳]ですか。", "tip": "答えは He's 12. や I'm 11 years old. の形。物に使うと「どれくらい古い」。年れいの質問でよく出る。"},
{"w": "What day is it today?", "m": "今日は何曜日ですか", "s": [], "ex": "[What day is it today]? I think it's Monday.", "ft": "[今日は何曜日]？月曜日だと思う。", "tip": "day は曜日を聞く。答えは It's Monday. の形。日付を聞くのは What's the date today? で、区別がよく出る。"},
{"w": "What's the date today?", "m": "今日は何月何日ですか", "s": [], "ex": "[What's the date today]? It's June 10.", "ft": "[今日は何月何日]？6月10日だよ。", "tip": "date は「日付」。答えは It's June 10. の形。曜日を聞く What day is it today? とのちがいに注意。"},
{"w": "What color ~?", "m": "何色の〜", "s": ["何色"], "ex": "[What color] do you like?", "ft": "あなたは[何色]が好きですか。", "tip": "色をたずねる。答えは I like blue. の形。What color is your bag?（かばんは何色？）のようにも使う。"},
{"w": "What kind of ~?", "m": "どんな種類の〜", "s": [], "ex": "[What kind of] music do you like?", "ft": "[どんな]音楽が好きですか。", "tip": "kind は「種類」。後ろに music や food を置く。答えは I like rock music. のように種類で答える。"},
{"w": "Where is ~?", "m": "〜はどこですか", "s": [], "ex": "[Where is] my cap? I can't find it.", "ft": "ぼくのぼうしは[どこ]？見つからない。", "tip": "場所をたずねる。答えは It's on the desk. のように in・on・under などで場所を言う。複数なら Where are ~?"},
// ---- Day4 ----
{"w": "Can I ~?", "m": "〜してもいいですか", "s": [], "ex": "[Can I] use your pen?", "ft": "あなたのペンを使っ[てもいいですか]。", "tip": "許可をもとめる言い方。答えは Sure.（いいよ）や Sorry.（ごめん）。May I ~? はよりていねいな形。"},
{"w": "Can you ~?", "m": "〜してくれますか", "s": ["〜できますか"], "ex": "[Can you] open the window?", "ft": "窓をあけ[てくれますか]。", "tip": "人にたのむ言い方。Can you swim? のように「〜できますか」の意味もある。答えは Sure. や OK. が多い。"},
{"w": "May I ~?", "m": "〜してもよろしいですか", "s": ["= Can I ~?"], "ex": "[May I] come in?", "ft": "入っ[てもよろしいですか]。", "tip": "Can I ~? よりていねいな言い方。先生や店の人に使う。答えは Sure. や Yes, you can. の形。"},
{"w": "Thank you for ~.", "m": "〜をありがとう", "s": [], "ex": "[Thank you for] the nice present.", "ft": "すてきなプレゼントを[ありがとう]。", "tip": "for の後ろに名詞か ~ing。Thank you for coming.（来てくれてありがとう）の形も出る。答えは You're welcome."},
{"w": "Welcome to ~.", "m": "〜へようこそ", "s": [], "ex": "[Welcome to] our school.", "ft": "私たちの学校へ[ようこそ]。", "tip": "to の後ろに場所を置く。Welcome to Japan.（日本へようこそ）の形でよく出る。Welcome home.（おかえり）も覚えたい。"},
{"w": "Nice to meet you.", "m": "はじめまして", "s": ["お会いできてうれしい"], "ex": "Hi, I'm Emi. [Nice to meet you].", "ft": "こんにちは、エミです。[はじめまして]。", "tip": "はじめて会った人へのあいさつ。答えは Nice to meet you, too. と too をつける。2回目からは Nice to see you."},
{"w": "How are you?", "m": "元気ですか", "s": ["ごきげんいかが"], "ex": "Hello, Mr. Brown. [How are you]?", "ft": "こんにちは、ブラウン先生。[お元気ですか]。", "tip": "答えは I'm fine, thank you.（元気です）や I'm good. の形。そのあと And you? と聞き返すのが決まり。"},
{"w": "See you.", "m": "またね", "s": ["= See you later."], "ex": "Bye, Tom. [See you] tomorrow.", "ft": "じゃあね、トム。[また]明日。", "tip": "別れるときのあいさつ。See you tomorrow.（また明日）、See you later.（またあとで）の形でよく出る。"},
{"w": "Have a nice day.", "m": "よい一日を", "s": ["いってらっしゃい"], "ex": "Bye, Ken. [Have a nice day].", "ft": "バイバイ、ケン。[よい一日を]。", "tip": "別れるときや出かける人に言う。答えは You, too.（あなたもね）。nice の代わりに good も使える。"},
{"w": "Excuse me.", "m": "すみません", "s": ["失礼します"], "ex": "[Excuse me]. Where is the station?", "ft": "[すみません]。駅はどこですか。", "tip": "人に話しかけるときの「すみません」。あやまるときの「ごめんなさい」は I'm sorry. この区別がよく出る。"},
{"w": "I'm sorry.", "m": "ごめんなさい", "s": ["残念に思う"], "ex": "[I'm sorry]. I can't go with you.", "ft": "[ごめんね]。いっしょに行けないんだ。", "tip": "あやまるときに使う。答えは That's OK.（だいじょうぶ）。I'm sorry I'm late. のように理由をつけることも多い。"},
{"w": "That's right.", "m": "その通り", "s": ["そうです"], "ex": "[That's right]. Ken is my brother.", "ft": "[その通り]。ケンは私の兄だ。", "tip": "相手の言ったことが正しいときに使う。right は「正しい」。Yes, that's right. の形もよく出る。"},
{"w": "That's OK.", "m": "だいじょうぶ", "s": ["いいですよ"], "ex": "[That's OK]. Don't worry.", "ft": "[だいじょうぶ]。気にしないで。", "tip": "I'm sorry.（ごめんね）への答えでよく出る。That's all right. も同じ意味。OK は大文字で書く。"},
{"w": "You're welcome.", "m": "どういたしまして", "s": [], "ex": "[You're welcome]. Come again soon.", "ft": "[どういたしまして]。またすぐ来てね。", "tip": "Thank you. への答え。welcome は「歓迎される」。No problem.（いいよ）も同じように使える。"},
{"w": "Here you are.", "m": "はい、どうぞ", "s": ["= Here it is."], "ex": "[Here you are]. This is your tea.", "ft": "[はい、どうぞ]。あなたのお茶だよ。", "tip": "物を手わたすときに言う。Can I have ~?（〜をもらえますか）への答えでよく出る。答えは Thank you."},
{"w": "Of course.", "m": "もちろん", "s": [], "ex": "[Of course], I can help you.", "ft": "[もちろん]手伝えるよ。", "tip": "「いいですか」と聞かれて「もちろん」と答えるときに使う。Sure. と同じ使い方。course の発音は「コース」。"},
{"w": "Me too.", "m": "私もです", "s": [], "ex": "[Me too]! I love pizza.", "ft": "[私も]！ピザが大好き。", "tip": "相手と同じ気持ちのときに使う短い答え。I like cats.（ねこが好き）→ Me too.（私も）の形で出る。"},
{"w": "Sure.", "m": "いいですよ", "s": ["もちろん"], "ex": "[Sure]. Here is my eraser.", "ft": "[いいよ]。はい、消しゴム。", "tip": "たのまれたときの「いいよ」。Can you ~? や Can I ~? への答えでよく出る。Of course. や OK. と同じ。"},
{"w": "Good luck.", "m": "がんばって", "s": ["幸運を祈る"], "ex": "[Good luck] on your test!", "ft": "テスト[がんばってね]！", "tip": "luck は「運」。試合やテストの前の人に言う。Good luck on ~ / with ~ の形も出る。答えは Thanks."},
{"w": "Let's see.", "m": "ええと", "s": ["そうですね"], "ex": "[Let's see]. I want this blue one.", "ft": "[ええと]。この青いのがほしいな。", "tip": "考えるときの「ええと」。Let's（〜しよう）と同じ形だけど、ここでは「ちょっと考えさせて」の意味。Let me see. も同じ。"},
{"w": "Just a minute.", "m": "ちょっと待って", "s": ["= Wait a minute."], "ex": "[Just a minute]. I'm coming.", "ft": "[ちょっと待って]。今行くよ。", "tip": "minute は「分」。1分だけ待っての気持ち。Just a moment. や Wait a minute. も同じ意味で出る。"},
{"w": "I see.", "m": "なるほど", "s": ["わかりました"], "ex": "[I see]. Thank you, Ms. Green.", "ft": "[なるほど]。ありがとう、グリーン先生。", "tip": "see は「見る」だけでなく「わかる」の意味もある。説明を聞いて「わかった」と言うときに使う。"},
{"w": "I think so.", "m": "そう思う", "s": [], "ex": "Ken is very kind. [I think so], too.", "ft": "ケンはとてもやさしい。私も[そう思う]。", "tip": "so は「そのように」。反対は I don't think so.（そうは思わない）。I think so, too.（私もそう思う）の形もよく出る。"},
{"w": "Come on.", "m": "さあ、早く", "s": ["がんばれ"], "ex": "[Come on], Ken! Let's go.", "ft": "[さあ]、ケン！行こう。", "tip": "人をさそったり急がせたりするときの「さあ」。試合で Come on! と言うと「がんばれ」の意味にもなる。"},
{"w": "Hurry up.", "m": "急いで", "s": ["早く"], "ex": "[Hurry up]! The bus is coming.", "ft": "[急いで]！バスが来るよ。", "tip": "hurry は「急ぐ」。up をつけて「急いで！」と強める。反対に「ゆっくりでいいよ」は Take your time."},
];
